CHANGELOG.md, README.md, pubspec.yaml
- Update CHANGELOG.md
- Add contributors in Readme.md.
=> :bookmark: Update version info.

CHANGELOG.md, lib/src/calendar_controller_provider.dart, lib/src/day_view/day_view.dart, lib/src/month_view/month_view.dart, lib/src/week_view/week_view.dart
Override didUpdateWidget method to update parameters on widget change.
=> :bug: fix: issue #62

lib/src/day_view/_internal_day_view_page.dart
LiveTimeIndicator was defined in a Stack, prior to Event tiles.
Thus it was displayed in background.
I moved the LiveTimeIndicator after the EventGenerator in the stack children.
I also added a IgnorePointer widget, since the LiveTimeIndicator Widget takes the whole agenda, if it catches gestures, event tiles cannot be pressed anymore.
Before:
After:
=> fix: Display LiveTimeIndicator in foreground

lib/src/day_view/day_view.dart, lib/src/extensions.dart, lib/src/month_view/month_view.dart, lib/src/week_view/week_view.dart
This changes removes time from `DateTime` object before calculating any difference between days.
=> :bug: Update calculation of day difference.

CHANGELOG.md, lib/src/components/day_view_components.dart, lib/src/event_controller.dart
Removing Full-Day Event Fixed 
#179 
=> fix: 🐛 Removing Full Day Event Fixed #179

lib/src/components/month_view_components.dart
The parameter "displayBorder" already existed for WeekDayTile, but setting it to False did not hide the weekday tile border. Now, setting displayBorder to False will cause the border to be null, not just 0 width.
Closes #191 
=> fix: :bug: DisplayBorder=false should hide border of WeekDayTile

lib/src/extensions.dart, lib/src/week_view/week_view.dart, lib/test/extensions_test.dart, pubspec.yaml
The issue is caused by the fact that `DateTimeExtensions` methods use `Duration` to move between adjacent days, and that approach is bugged in the events of Daylight Saving Time (Sun, Mar 26, 2023 2:00 AM and Sun, Oct 29, 2023 3:00 AM).
- Create a week view calendar
- Set week startDay on **sunday**
- Create events that span on days: 2023-03-27 - 2023-04-01
- Fixed `DateTimeExtensions` methods to use `DateTime` constructor instead of adding `Duration`
- Added unit testing to project
- Added tests in new test/extensions_test.dart testing file that verifies that the issue is fixed.
- Fixing and deprecating `dateYMD` method in `DateTimeExtensions`
- This method was unused, bugged and was supposed to do the same thing as `withoutTime` method.
- Fixing one place in week_view.dart file which …
=> fix: some DateTimeExtensions methods are not working properly for Daylight Saving Time

lib/src/day_view/day_view.dart, lib/src/week_view/week_view.dart
Fixed Header style color issue.
#199 
=> fix: Header style color issue

example/lib/widgets/day_view_widget.dart, lib/src/components/_internal_components.dart, lib/src/components/day_view_components.dart, lib/src/day_view/_internal_day_view_page.dart, lib/src/day_view/day_view.dart, lib/src/enumerations.dart, lib/src/modals.dart, lib/src/painters.dart
This PR adds the ability to show half hours on the timeline of the Day View:
#223
=> feat: ✨ Added half hour support for the Day View timeline

CHANGELOG.md, lib/src/components/day_view_components.dart, lib/src/day_view/_internal_day_view_page.dart, lib/src/week_view/_internal_week_view_page.dart
=> fix: 🐛Unwanted space at top of dayView while using sliver #225.

CHANGELOG.md, lib/src/day_view/day_view.dart, lib/src/month_view/month_view.dart, lib/src/typedefs.dart, lib/src/week_view/week_view.dart
=> fix: 🐛Added a callback for the header title #241.

lib/src/month_view/month_view.dart
This change allows for adding a specific `ScrollPhysics` to the month view, for the month view's pages.
In my case, I have the `MonthView` nested somewhere in a sliver of a `CustomScrollView` and the month view page's `GridView` suddenly takes the "scroll focus" while I just want it never to scroll. This option allows me to pass in a `NeverScrollableScrollPhysics` which fixes the issue.
No breaking changes
If the PR is breaking, uncomment this header and add instructions for how to migrate from the
currently released version to the new proposed way.
-->
Fixes #178 
=> fix: Customize ScrollPhysics for MonthView

lib/src/components/_internal_components.dart, lib/src/extensions.dart, pubspec.yaml, test/extensions_test.dart
Improve the LiveTimeIndicator to set the state only when the current hour and minute changes.
This PR removes unnecessary rebuilds every second. Instead, it will only rebuild the timeline when the current hour or minute will change.
None
=> :fix: Improve the LiveTimeIndicator performance.

CHANGELOG.md, lib/src/calendar_event_data.dart, lib/src/event_arrangers/event_arrangers.dart, lib/src/event_arrangers/merge_event_arranger.dart, lib/src/event_arrangers/side_event_arranger.dart, test/event_arranger_test/merge_event_arranger_test.dart
This PR Adds the option to decide whether to include the edge while merging the overlapping events or not. It adds a new flag `includeEdge` in `MergeEventArranger` and `SideEventArranger` that will decide whether the events that overlaps on the edge should be merged or not. I've attached 2 image of `SideEventArranger` one with `includeEdge` true another with false.
includeEdge: true
includeEdge: false
This will fix the issue #290 .
=> :feat: Adds includeEdge flag in EventArrangers.

CHANGELOG.md, lib/src/event_controller.dart, lib/src/extensions.dart
Removes the force unwrap on `startTime` in `addEventInSortedManner` method of `MyList` extension. This will fix the issue that was occurring while adding the events without `startTime`.
Fixes issue #282 .
=> ✨ Removes force unwrap while sorting the events.

CHANGELOG.md, README.md, lib/src/day_view/day_view.dart, lib/src/month_view/month_view.dart, lib/src/week_view/week_view.dart
- In DayView, MonthView, and WeekView hidden methods are added for hiding header.
- In `MonthView` I added the class `MonthHeader`. Inside the `MonthHeader` class added a `hidden` method to hide the header widget. To hide a header inside the `MonthView` widget we can use like `headerBuilder: MonthHeader.hidden`.
- In `WeekView` I added the class `WeekHeader`. Inside the `WeekHeader` class added a `hidden` method to hide the header widget. To hide a header inside the `WeekView` widget we can use like `weekPageHeaderBuilder: WeekHeader.hidden`.
- In `DayView` I added the class `DayHeader`. Inside the `DayHeader` class added a `hidden` method to hide the header widget. To hide a header inside the `DayView` widget we can use like `dayTitleBuilder: DayHeader.hidden`.
#299 
[Contributor Guide]: …
=> fix: 🐛Header view hidden functionality added #299.

CHANGELOG.md, pubspec.yaml
Updated plugin's version and revised changelist.
None
=> 🔖 Version bump 1.1.0.

analysis_options.yaml, example/macos/.gitignore, lib/src/calendar_event_data.dart, lib/src/day_view/day_view.dart, lib/src/event_arrangers/merge_event_arranger.dart, lib/src/event_arrangers/side_event_arranger.dart, lib/src/event_controller.dart, lib/src/painters.dart, lib/src/week_view/week_view.dart, pubspec.yaml
- Use lints package for static analysis.
=> feat: fixes static analysis warning in package.

CHANGELOG.md, lib/src/components/_internal_components.dart
- The size of the LiveTimeLine's painting area is now determined by the screen size that I've adjusted, and it has been replaced by LiveTimeIndicatorSettings.height.
#332 
=> fix: 🐛onDateTap triggered issue resolved by changing customPaint height #332.

lib/src/components/common_components.dart, lib/src/day_view/day_view.dart, lib/src/week_view/week_view.dart
- Create common widgets which being used as widget function in both day and week view.
=> refactor code of day week view

lib/src/components/common_components.dart, lib/src/day_view/day_view.dart, lib/src/week_view/week_view.dart
- add startHour minutes (startHour * 60) to DateTime which then passed as arguments to onDateTap
Closes #341 
=> fix: 🐛 onDateTap return wrong date when startHour is set #341

CHANGELOG.md, lib/src/month_view/month_view.dart, lib/src/week_view/week_view.dart
- Add pageViewPhysics for week and month view to change scroll behaviour of page view
Closes #314 
=> fix: 🐛 lock horizontal scroll for week and month view #314

CONTRIBUTING.md
The command `flutter format .` has been updated as `dart format .` 
This PR updates the CONTRIBUTING.md doc to reflect this change
=> docs: Fixes CONTRIBUTING.md referencing old flutter format command 

lib/src/components/_internal_components.dart
Fixes: #336 
Updates the visibility check on the timeline hour to keep it displayed if both `showTime` and `showTimeBackgroundView` on the `LiveTimeIndicator` are not enabled. 
Currently if both `showTime` and `showTimeBackgroundView` display are both disabled the hours next to the current time disappears 15 minutes before and after to prevent overlap.
With this change the hour in the timeline will disappear only if both `showTime` and `showTimeBackgroundView` are enabled in the `liveTimeIndicatorSettings`.
Closes #336 
=> fix: add check to keep hour in timeline (in day and week view) if LiveTimeIndicator time or bubble dosen't overlap.

CHANGELOG.md, README.md, lib/src/components/_internal_components.dart, lib/src/components/month_view_components.dart, lib/src/day_view/_internal_day_view_page.dart, lib/src/day_view/day_view.dart, lib/src/month_view/month_view.dart, lib/src/week_view/_internal_week_view_page.dart, lib/src/week_view/week_view.dart
Added support for double tap on any event in day, week, month view.
Closes #195
=> feat: ✨add on event double tap callback in day, week, month view

CHANGELOG.md, README.md, example/lib/widgets/month_view_widget.dart, lib/src/components/month_view_components.dart, lib/src/month_view/month_view.dart, lib/src/typedefs.dart
- hideDayNotInMonth added. It by default false. It set to true to hide date which not is in current month.
Closes #328 
=> fix: 🐛hide month days not in current month functionality added #328.

CHANGELOG.md
=> docs: CHANGELOG.md updated

CHANGELOG.md, lib/src/day_view/_internal_day_view_page.dart
=> 🐛 Fixes issue #386.

CHANGELOG.md, example/pubspec.yaml, lib/src/components/_internal_components.dart, lib/src/week_view/_internal_week_view_page.dart
Fixes issue in quarter hour display when start hour is provided.
Closes #387
=> 🐛 Fixes issue in quarter hours when startHour is provided. #387

.github/workflows/github_pages.yml, CHANGELOG.md, example/web/index.html, lib/src/calendar_event_data.dart, lib/src/event_arrangers/merge_event_arranger.dart, lib/src/event_arrangers/side_event_arranger.dart, lib/src/extensions.dart
Refactor code of `SideEventArranger`. This PR implements a new way of arranging the events side by side.
Also, this PR updates example and GitHubaction to use flutter 3.24.3.
Closes #290
=> 🐛 Fixes issue #290.

CHANGELOG.md, docs/migration_guide.md, lib/calendar_view.dart, lib/src/components/common_components.dart, lib/src/components/components.dart, lib/src/components/day_view_components.dart, lib/src/components/headers/calendar_page_header.dart, lib/src/components/headers/day_page_header.dart, lib/src/components/headers/month_page_header.dart, lib/src/components/headers/week_page_header.dart, lib/src/components/month_view_components.dart, lib/src/components/week_view_components.dart, lib/src/day_view/day_view.dart, lib/src/month_view/month_view.dart, lib/src/style/header_style.dart, lib/src/week_view/week_view.dart
- Adds additional configurations for `HeaderStyle`.
- Added `mainAxisSize`, `mainAxisAlignment`, `rightIconConfig` and `leftIconConfig`.
- Adds additional configurations for `CalendarPageHeader`, `MonthPageHeader`, `DayPageHeader` and `WeekPageHeader`.
- Added `titleBuilder` to build custom title for header.
- `Deprecations`:
- deprecated `backgroundColor` and `iconColor` from `CalendarPageHeader`, `DayPageHeader`, `MonthPageHeader` and `WeekPageHeader`.
- **Solution:** use `headerStyle` instead.
- deprecated `leftIconVisible`, `rightIconVisible`, `leftIconPadding`, `rightIconPadding`, `leftIcon` and `rightIcon` from `HeaderStyle`.
- **Solution:** use `rightIconConfig` and `leftIconConfig` instead.
Though this PR does not have any breaking changes, it has many deprecations which will be …
=> ✨ Provide more configurations for page headers.

CHANGELOG.md, example/lib/widgets/day_view_widget.dart, example/lib/widgets/week_view_widget.dart, lib/src/day_view/_internal_day_view_page.dart, lib/src/day_view/day_view.dart, lib/src/week_view/_internal_week_view_page.dart, lib/src/week_view/week_view.dart
- Updated unused property `scrollPhysics` in `DayView` & given scroll physics to `SingleChildScrollView` in `InternalDayViewPage`.
- Added `scrollPhysics` in week-view & day-view to control the scrolling behaviour.
Closes #417
=> fix: Fixes issue #417: 🐛 Fixes calendar scroll physics for day & week view

CHANGELOG.md, example/lib/widgets/day_view_widget.dart, example/lib/widgets/week_view_widget.dart, lib/src/components/_internal_components.dart, lib/src/day_view/_internal_day_view_page.dart, lib/src/day_view/day_view.dart, lib/src/typedefs.dart, lib/src/week_view/_internal_week_view_page.dart, lib/src/week_view/week_view.dart
- Used callback to get the timestamp of tapped timeline & execute the given function.
Closes issue: #383
=> feat: Fixes issue #383: ✨ Add action on tap of timestamp in day & week view

CHANGELOG.md, example/lib/widgets/day_view_widget.dart, example/lib/widgets/week_view_widget.dart, lib/src/event_arrangers/side_event_arranger.dart
Use `maxWidth` to define the maximum width of event slot. If enough space is available, the event slot will use the specified max width. Otherwise, it will reduce to fit all events in the cell. If max width is not specified, slots will expand to fill the cell.
Closes #413 
=> feat: Fixes issue #413: Set max width of event slot in week & day view

CHANGELOG.md, README.md, example/lib/widgets/month_view_widget.dart, example/lib/widgets/week_view_widget.dart, lib/src/extensions.dart, lib/src/month_view/month_view.dart, lib/src/week_view/week_view.dart
- Fixed if `daysNotInMonth` true hide events on hidden date.
- Added `showWeekends` flag to hide weekends. Default value is true.
- Removed empty rows if entire week dates doesn't fall in current month.
- Updated readme & change log
- Attached GIF which shows example.
Closses #385 
=> feat: Fixes issue #385: Add `showWeekends` flag in month view

CHANGELOG.md, example/lib/extension.dart, example/lib/widgets/month_view_widget.dart, lib/src/components/month_view_components.dart, lib/src/extensions.dart, lib/src/month_view/month_view.dart
- Fixes analytics issue usage of deprecated colors. 
- Fixes `titleColor` of date for `hideDaysNotInMonth: false`.
=> fix: 🔨 Fixes analytics issue

CHANGELOG.md, lib/src/week_view/week_view.dart
- Fixed new startHour and endHour not updating.
Closes #410 
=> fix: Fixes issue #410: 🐛 Fix `startHour` and `endHour` rebuild issue in WeekView

CHANGELOG.md, lib/src/month_view/month_view.dart
- Fixed tap issue: If  `hideDaysNotInMonth`: true in month view then in default filled cell `onTileDoubleTap` & `onTileLongTap` is not working.
Related issue: #435 
=> fix: Fixes issue #435: 🐛 Fix tap issue for days not in month

CHANGELOG.md, example/lib/constants.dart, example/lib/main.dart, example/lib/pages/event_details_page.dart, example/lib/widgets/add_event_form.dart, example/lib/widgets/day_view_widget.dart, example/lib/widgets/delete_event_dialog.dart, example/lib/widgets/month_view_widget.dart, example/lib/widgets/week_view_widget.dart, lib/src/calendar_event_data.dart, lib/src/enumerations.dart, lib/src/event_controller.dart, lib/src/modals.dart, lib/src/month_view/month_view.dart
1. Added support in month view, day view & week view .
2. Supported repeat modes: Do no repeat, daily, weekly, monthly & yearly.
3. Supported recurrence end: Never, on given date & till given interval.
4. Edit will apply to all repeating events.
5. Deletes a recurring event based on the specified deletion type: Current, Following, All occurrence.
6. Support for ranging events are not added due to open issues: #23 
| ![Image 1](https://github.com/user-attachments/assets/d355da4a-63ae-4dcb-a128-5b828586aab3) |
|:--:|
| Do not repeat |
| ![Image 1](https://github.com/user-attachments/assets/45b3077a-fe70-465a-ad61-40d27ce75f63) | ![Image 2](https://github.com/user-attachments/assets/7dae25af-cea9-4885-a35b-d99ed3a9d564) | ![Image 3](https://github.com/user-attachments/assets/66a2e329-0cd8-475 …
=> feat: Fixes issue #378: ✨ Add support for single day & full day recurring events

CHANGELOG.md, lib/src/components/headers/calendar_page_header.dart, lib/src/components/headers/day_page_header.dart, lib/src/components/headers/month_page_header.dart, lib/src/components/headers/week_page_header.dart, lib/src/day_view/day_view.dart, lib/src/month_view/month_view.dart, lib/src/week_view/week_view.dart
- Fixed previous and next icons if end dates are reached (Min and max dates) in header style month, day & weekview.
- Fixed inconsistent padding issue of right icon in the `HeaderStyle`.
- Disable previous & next icons
Closes #426 
=> fix: Fixes issue #426: 🐛 Fix header style icons visibility on min & max dates

README.md, lib/src/event_controller.dart, test/src/event_controller_test.dart
=> feat: Added 'clear' method to EventController.

CHANGELOG.md, README.md, lib/src/components/month_view_components.dart, lib/src/month_view/month_view.dart, lib/src/typedefs.dart
- Added `onEventTap`, `onEventDoubleTap` & `onEventLongTap` gesture recognizers to get tap details.
- Added tap details callback in `FilledCell`.
Closes issue: #390 
=> feat: Fixes issue #390: ✨ Add tap details callback in month view

lib/src/week_view/_internal_week_view_page.dart
WeekView hourLinePainter does not work， I have made repairs
Closes #461
=> fix : fixes hourLinePainter of weekView，fixes issue #461

CHANGELOG.md, lib/src/components/_internal_components.dart
Fixed Splash issue on timeline in `WeekView` and `DayView` when `onTimestampTap` is null
- Updated login on the tap of the inkwell so now it will work as expected.
Closes #459 
=> fix : 🐛 Fixed Splash issue on timeline in `WeekView` and `DayView` when `onTimestampTap` is null.(#459)
