SimformSolutionsPvtLtd/flutter_calendar_view

example/lib/create_event_page.dart, example/lib/day_view_page.dart, example/lib/month_view_page.dart, example/lib/week_view_page.dart, example/pubspec.yaml, lib/src/calendar_event_data.dart, lib/src/components/_internal_components.dart, lib/src/components/month_view_components.dart, lib/src/constants.dart, lib/src/day_view/_internal_day_view_page.dart, lib/src/day_view/day_view.dart, lib/src/month_view/month_view.dart, lib/src/painters.dart, lib/src/week_view/_internal_week_view_page.dart, lib/src/week_view/week_view.dart
Made some UI improvements and Code refactor.
=> Refactor/code refactor and UI changes

CHANGELOG.md, lib/src/extensions.dart, lib/src/week_view/week_view.dart
- Update week calculation logic.
=> :bug: fix: issue #48

.github/workflows/flutter_analyze.yml, .github/workflows/github_pages.yml
Update Github actions to use latest flutter version for analysis and build.
=> Update Github actions to use latest flutter version.

CHANGELOG.md, lib/src/month_view/month_view.dart
- Wrap all the children of Row with expanded. in MonthView _weekBuilder.
=> :bug: fix: issue #42

CHANGELOG.md, lib/src/calendar_controller_provider.dart, lib/src/calendar_event_data.dart, lib/src/components/_internal_components.dart, lib/src/components/month_view_components.dart, lib/src/day_view/_internal_day_view_page.dart, lib/src/day_view/day_view.dart, lib/src/event_arrangers/event_arrangers.dart, lib/src/event_arrangers/merge_event_arranger.dart, lib/src/event_arrangers/side_event_arranger.dart, lib/src/event_controller.dart, lib/src/month_view/month_view.dart, lib/src/typedefs.dart, lib/src/week_view/_internal_week_view_page.dart, lib/src/week_view/week_view.dart
Add strict typecast in generics.
=> :bug: fix: issue #65

CHANGELOG.md, lib/src/extensions.dart, lib/src/week_view/week_view.dart, pubspec.yaml
Update package version
Update CHANGELOG.md
=> :bookmark: calculate week difference based on start day.

CHANGELOG.md, lib/src/calendar_event_data.dart, lib/src/event_controller.dart, lib/src/extensions.dart
- Added method to update filter.
- Removed tree structure to store single events. Use map instead.
- Add comparison for startTime and endTime in CalendarEventData.
=> :sparkles: Update event controls.

lib/src/day_view/day_view.dart, lib/src/month_view/month_view.dart, lib/src/week_view/week_view.dart
This chages updates the controller of underlying Calendar view every time when `didChangeDependencies` is called.
=> :bug: Update controller on `didChangeDependencies` method.

lib/src/day_view/day_view.dart
Issue 93 fixed
Showing only 1 day in DayView
=> Showing only 1 day in DayView

lib/src/components/month_view_components.dart, lib/src/components/week_view_components.dart, lib/src/month_view/month_view.dart, lib/src/week_view/week_view.dart
Support for locale in month view and week view
=> Support for locale in month view and week view

lib/src/components/common_components.dart, lib/src/components/day_view_components.dart, lib/src/components/month_view_components.dart, lib/src/components/week_view_components.dart
Add Week page header color customization
=> Add Week page header color customization

README.md, example/android/app/src/main/AndroidManifest.xml, lib/src/event_controller.dart
Signed-off-by: Mehul Kabaria <mehul.kabaria@gmail.com>
=> 🐛 : Duplicate item in cells while adding events in the same session #61

CHANGELOG.md, README.md
=> Updated Readme

lib/calendar_view.dart, lib/src/components/common_components.dart, lib/src/components/day_view_components.dart, lib/src/components/month_view_components.dart, lib/src/components/week_view_components.dart, lib/src/day_view/day_view.dart, lib/src/month_view/month_view.dart, lib/src/style/header_style.dart, lib/src/week_view/week_view.dart
Header Style customization without builders #34
=> Header Style customization without builders

lib/src/event_controller.dart
=> Fix same event on same time

lib/src/components/_internal_components.dart, lib/src/components/day_view_components.dart, lib/src/day_view/_internal_day_view_page.dart, lib/src/day_view/day_view.dart, lib/src/event_arrangers/event_arrangers.dart, lib/src/event_arrangers/merge_event_arranger.dart, lib/src/event_arrangers/side_event_arranger.dart
Change starting time of day view issue #57 #102
=> Change starting time of day view

lib/src/components/_internal_components.dart, lib/src/event_arrangers/event_arrangers.dart, lib/src/event_arrangers/merge_event_arranger.dart, lib/src/event_arrangers/side_event_arranger.dart, lib/src/event_controller.dart
=> :sparkles: update logic in side event arranger.

lib/src/extensions.dart
This PR gets the changes from PR #104 after rebase. Close #104  if this gets merge.
=> Compare dates in utc time to avoid DST disalignment

example/ios/Podfile, example/macos/Podfile, lib/src/components/_internal_components.dart, lib/src/day_view/_internal_day_view_page.dart, lib/src/day_view/day_view.dart, lib/src/extensions.dart, lib/src/typedefs.dart, lib/src/week_view/_internal_week_view_page.dart, lib/src/week_view/week_view.dart
This PR takes changes from PR #105. Close PR #105  if this gets merged.
=> Rebase francescovgg/feature/on date tap

lib/src/week_view/_internal_week_view_page.dart
=> Fix: week day not align center.

lib/src/typedefs.dart, lib/src/week_view/_internal_week_view_page.dart, lib/src/week_view/week_view.dart
=> WeekView support show current week number.

.github/workflows/pull_request_template.md
Added pull_request_template.md file
=> Added pull_request_template.md file

lib/src/calendar_event_data.dart, lib/src/components/day_view_components.dart, lib/src/day_view/_internal_day_view_page.dart, lib/src/day_view/day_view.dart, lib/src/event_controller.dart, lib/src/extensions.dart, lib/src/typedefs.dart, lib/src/week_view/_internal_week_view_page.dart, lib/src/week_view/week_view.dart
=> Full day event support

CHANGELOG.md, README.md, lib/src/day_view/day_view.dart, lib/src/week_view/week_view.dart
Updated README.md and CHANGELOG.md file 
=> Updated README.md and CHANGELOG.md file

CHANGELOG.md, CONTRIBUTING.md
=> 📚 CONTRIBUTING.md file updated with proper document

CONTRIBUTING.md, pubspec.yaml
=> 🔖 Version bump 1.0.2

README.md
=> 📚 README.md updated.

lib/src/day_view/_internal_day_view_page.dart, lib/src/day_view/day_view.dart, lib/src/typedefs.dart, lib/src/week_view/_internal_week_view_page.dart, lib/src/week_view/week_view.dart
Press detector builder for week view and day view. from PR #120 
=> feat: ✨ Press Detector builder for day view and week view

analysis_options.yaml, lib/src/calendar_event_data.dart, lib/src/components/month_view_components.dart, lib/src/day_view/day_view.dart, lib/src/week_view/week_view.dart
Added text style and description style in CalendarEventData #147
Fixes #147 
=> feat: ✨ Added text style and description style in CalendarEventData #147

CHANGELOG.md, lib/src/day_view/day_view.dart, lib/src/week_view/week_view.dart
Animate to specific scroll controller offset. from PR #94
=> feat: ✨ Animate to specific scroll controller offset. from PR #94

CHANGELOG.md, lib/src/constants.dart, lib/src/event_arrangers/event_arrangers.dart, lib/src/event_arrangers/merge_event_arranger.dart, lib/src/event_arrangers/side_event_arranger.dart, pubspec.yaml
=> fix: 🐛 Event till 12 am

CHANGELOG.md
=> docs: 📚 CHANGELOG.md updated

pubspec.yaml
=> 🔖 Version bump 1.0.3

.gitignore, test/extensions_test.dart
=> fix: 🐛 Test folder location update

CHANGELOG.md, lib/src/month_view/month_view.dart
=> fix: 🐛 SafeArea issue fixed with month view #205

CHANGELOG.md, example/lib/pages/create_event_page.dart, lib/src/day_view/day_view.dart, lib/src/week_view/week_view.dart
=> fix: 🐛Fixed week-view & day-view layout issue in landscape mode #237.

lib/src/event_controller.dart, lib/src/extensions.dart, lib/src/typedefs.dart, test/custom_sort_test.dart
Allows for adding a custom sort function. The fallback will be the default startTimeWise sorting. This will be used if no sorter was added or if the sorter returns `0`.
=> feat: Add custom sort for EventController

lib/src/components/month_view_components.dart
=> fix: `month_view` event `titleStyle` is tied to specific cell index

CHANGELOG.md
=> feat: correct release date in CHANGELOG.md.

CHANGELOG.md
=> docs: CHANGELOG.md updated

lib/src/week_view/_internal_week_view_page.dart
Fix #259
Fix the position of the full day event on the week view.
Before:
After:
=> fix: Display full day events on correct date on weekView

README.md, example/lib/widgets/day_view_widget.dart, example/lib/widgets/month_view_widget.dart, example/lib/widgets/week_view_widget.dart, lib/src/components/_internal_components.dart, lib/src/components/month_view_components.dart, lib/src/day_view/_internal_day_view_page.dart, lib/src/day_view/day_view.dart, lib/src/month_view/month_view.dart, lib/src/week_view/_internal_week_view_page.dart, lib/src/week_view/week_view.dart
=> feat: Added support for event long-press method execution

CHANGELOG.md, README.md, lib/src/components/_internal_components.dart, lib/src/day_view/_internal_day_view_page.dart, lib/src/day_view/day_view.dart, lib/src/painters.dart, lib/src/typedefs.dart, lib/src/week_view/_internal_week_view_page.dart, lib/src/week_view/week_view.dart
- Added end time support for day and weeek view to set end time of day and week.
Closes #298 
=> fix: 🐛 change end time for day and week view #298

CHANGELOG.md, README.md, lib/src/month_view/month_view.dart
- Show border will apply also to header in month view with showBorder field.
- **showBorder : false**
- **showWeekTileBorder : false**
Closes #306 
=> fix: 🐛 fix show border not applying to header in month view #306

CHANGELOG.md, README.md, pubspec.yaml
Version bump to 1.2.0 and revised changelog file
=> 🔖 version bump 1.2.0

lib/src/day_view/_internal_day_view_page.dart, lib/src/week_view/_internal_week_view_page.dart
Adds generic in InternalDayViewPage.
=> Fix Issue 380

CHANGELOG.md, lib/src/components/headers/calendar_page_header.dart
- Fixed right icon always shows default icon when providing custom icon in header style.
Closes issue: #432 
=> fix: Fixes issue #432: 🐛 Fixes right icon always shows default icon

CHANGELOG.md, README.md
- Added argument in `cellBuilder` example
Closes issue: #433 
=> docs: Fixes issue #433: 📝 Update documentation `hideDaysNotInMonth` argument in cellBuilder

CHANGELOG.md, lib/src/components/headers/calendar_page_header.dart, lib/src/components/headers/day_page_header.dart, lib/src/components/headers/month_page_header.dart, lib/src/components/headers/week_page_header.dart
- Fixes issue of header icon `color` property in `IconDataConfig`
```
headerStyle: HeaderStyle(
leftIconConfig: IconDataConfig(
color: Colors.green,
),
rightIconConfig: IconDataConfig(
color: Colors.green,
),
),
```
=> fix: 🔨 Fix header icon color issue

CHANGELOG.md, pubspec.yaml
1. Updated changelog.
2. Updated version in pubspec.
3. Checked pub points: 160/160.
4. Dry run has 575 analytics issues considering it in future release.
=> release: 🔖 version bump 1.4.0

CHANGELOG.md
=> docs: 📝 Update changelog

example/lib/widgets/add_event_form.dart, lib/src/day_view/day_view.dart, lib/src/month_view/month_view.dart
- Updated the event end date logic by utilising recurrenceEnd type and its value for handling recurring events appropriately.
=> fix: 🐛Fix recurring event not shown issue

example/lib/widgets/add_event_form.dart, example/lib/widgets/date_time_selector.dart, lib/src/components/_internal_components.dart, lib/src/event_arrangers/event_arrangers.dart, lib/src/event_arrangers/merge_event_arranger.dart, lib/src/event_arrangers/side_event_arranger.dart, lib/src/event_controller.dart, test/event_arranger_test/merge_event_arranger_test.dart
- Add support for multi-day events
- Resolved issue of event not getting added till midnight
Closes #333 , #23
=> feat: ✨Add support for multi-day events

README.md, lib/src/components/_internal_components.dart, lib/src/day_view/day_view.dart, lib/src/modals.dart, lib/src/month_view/month_view.dart
✨Add support for custom time provider in live time indicator
Closes #460 
=> feat: ✨Add support for custom time provider in live time indicator

CHANGELOG.md, pubspec.yaml
- Bumped version to v2.0.0
- Updated changelog.md
=> chore: 🔖 version bump from 1.4.0 to 2.0.0
